// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AplLanguageVS
{
				static class Vsix
				{
								public const string Id = "eb8babe5-7612-40db-81d1-86d60aff9d43";
								public const string Name = "APL Language";
								public const string Description = @"Adds APL Language support";
								public const string Language = "en-US";
								public const string Version = "1.0";
								public const string Author = "Gilgamesh Athoraya";
								public const string Tags = "icon, file, image, textmate, language, apl";
				}
}
